driver.get("https://www.calculator.net/random-number-generator.html")
lower_limit.send_keys("100")
upper_limit.send_keys("500")
generate_button = driver.find_element(By.NAME, "x")
generate_button.click()